### ISSUE TITLE
Forecast issue

### ISSUE THREAD

**Issue by marktillo** [ibBogdan/lovelace-htc-flipclock-weather#1]
Great plugin!!
I'm having an issue with the four day forecast showing today's date on all, can you point me as to where I'm going wrong, using the dark sky weather as source 🤪

**Comment by ibBogdan** [comment]
> Great plugin!!
> I'm having an issue with the four day forecast showing today's date on all, can you point me as to where I'm going wrong, using the dark sky weather as source

can i get a print screen of your yaml and the output, please?
also, do you have time_date sensors active? 
that`s really weird:))

**Comment by marktillo** [comment]
![Screen Shot 2020-09-17 at 21 05 35](https://user-images.githubusercontent.com/32182400/93522588-a080ea80-f929-11ea-8b30-31e6a245f6f3.png)
![Screen Shot 2020-09-17 at 21 05 12](https://user-images.githubusercontent.com/32182400/93522613-a8d92580-f929-11ea-9933-277d1116ac84.png)
![Screen Shot 2020-09-17 at 21 07 32](https://user-images.githubusercontent.com/32182400/93522788-ea69d080-f929-11ea-9413-6ad85f061c30.png)
hope the screen shots help with the head scratching haha, also I'm getting an hour difference on safari browser and chrome 
![Screen Shot 2020-09-17 at 21 10 13](https://user-images.githubusercontent.com/32182400/93522992-3f0d4b80-f92a-11ea-9971-27ce17e007bc.png)

**Comment by marktillo** [comment]
just a thought, looking at my own screen shots!?! forecast 4 says FRI, which leads me to do some mental math and guess the forecast is doing hourly rather than days???

**Comment by ibBogdan** [comment]
![image](https://user-images.githubusercontent.com/12171894/93592370-ba1e4280-f9ba-11ea-8e5b-e4b9eb6323fd.png)
this is my darksky forecast. try updating the hourly forecast. maybe that`s what`s causing the issue.
