### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by bluenazgul** [ibBogdan/lovelace-htc-flipclock-weather#16]
i followed your guide but i cant get it working

**Comment by AndreB52** [comment]
here te same problem
resources:
  - url: /local/custom_ui/htc-weather/htc-flipclock-weather.js?v1.3.0
    type: module
not possible in the raw config  accoording HA
instead i had to place /local/custom_ui/htc-weather/htc-flipclock-weather.js?v1.3.0 in the resources.

Card is not showing
Also
sensor:
platform: time_date
display_options:
    - time
    - date
    - date_time
    - date_time_utc
    - date_time_iso
    - time_date
    - time_utc
    - beat
    placed in the config.yaml  is not working
logs: 
2021-11-04 16:34:41 ERROR (MainThread) [homeassistant.setup] Setup failed for platform: Integration not found.
2021-11-04 16:34:41 ERROR (MainThread) [homeassistant.setup] Setup failed for display_options: Integration not found.
I am doing something wrong, but don't know what

**Comment by yfands** [comment]
Hello AndreB52, check the indentation...

```
   platform: time_date
   display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
```

**Comment by curtisdr** [comment]
Not sure if this was proper, but for it to work I had to change the Lovelace Resource to 
`/local/custom_ui/htc-weather/htc-flipclock-weather.js`

**Comment by GerdRuetten** [comment]
> check the console and tell me what the error is. or any lovelace errors?

Hi,
i get this error in the browser-console:

`htc-flipclock-weather.js:114  HTC Flip Clock  1.3.0 
htc-flipclock-weather.js:195 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at HtcWeather.render (htc-flipclock-weather.js:195:40)
    at HtcWeather.shouldUpdate (htc-flipclock-weather.js:167:18)
    at HtcWeather.performUpdate (updating-element.js?module:473:14)
    at HtcWeather._enqueueUpdate (updating-element.js?module:437:25)
render @ htc-flipclock-weather.js:195
shouldUpdate @ htc-flipclock-weather.js:167
performUpdate @ updating-element.js?module:473
_enqueueUpdate @ updating-element.js?module:437
await in _enqueueUpdate (async)
requestUpdate @ updating-element.js?module:416
set @ updating-element.js?module:161
setConfig @ htc-flipclock-weather.js:161
s @ ha-logbook.ts:28
(anonym) @ ha-logbook.ts:28
d @ ha-logbook.ts:28
l @ ha-logbook.ts:28
v @ ha-logbook.ts:28
value @ hui-masonry-view.ts:44
(anonym) @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
performUpdate @ styles.ts:366
scheduleUpdate @ styles.ts:366
_$EC @ styles.ts:366
await in _$EC (async)
requestUpdate @ styles.ts:366
o @ styles.ts:366
m @ styles.ts:366
i @ hui-masonry-view.ts:44
value @ hui-root.ts:495
(anonym) @ ha-panel-lovelace.ts:144
(anonym) @ typography.js:181
setTimeout (async)
(anonym) @ typography.js:181
handleEvent @ styles.ts:366
i @ typography.js:181
(anonym) @ ha-logbook.ts:28
Promise.then (async)
(anonym) @ ha-logbook.ts:28
d @ ha-logbook.ts:28
l @ ha-logbook.ts:28
v @ ha-logbook.ts:28
value @ hui-masonry-view.ts:44
(anonym) @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
performUpdate @ styles.ts:366
scheduleUpdate @ styles.ts:366
_$EC @ styles.ts:366
await in _$EC (async)
requestUpdate @ styles.ts:366
o @ styles.ts:366
m @ styles.ts:366
i @ hui-masonry-view.ts:44
value @ hui-root.ts:495
(anonym) @ hui-root.ts:495
setTimeout (async)
(anonym) @ ed7c25f5.js:1
(anonym) @ 5180cdb1.js:1
requestAnimationFrame (async)
window.requestAnimationFrame @ 5180cdb1.js:1
i @ ed7c25f5.js:1
value @ hui-root.ts:495
_$AE @ styles.ts:366
performUpdate @ styles.ts:366
scheduleUpdate @ styles.ts:366
_$EC @ styles.ts:366
await in _$EC (async)
requestUpdate @ styles.ts:366
o @ styles.ts:366
m @ styles.ts:366
_ @ styles.ts:366
P @ ha-panel-lovelace.ts:144
p @ styles.ts:366
T @ styles.ts:366
_$AI @ styles.ts:366
S @ styles.ts:366
update @ styles.ts:366
performUpdate @ styles.ts:366
scheduleUpdate @ styles.ts:366
_$EC @ styles.ts:366
await in _$EC (async)
requestUpdate @ styles.ts:366
set @ styles.ts:366
value @ ha-panel-lovelace.ts:144
await in value (async)
value @ ha-panel-lovelace.ts:144
_$AE @ styles.ts:366
performUpdate @ styles.ts:366
scheduleUpdate @ styles.ts:366
_$EC @ styles.ts:366
await in _$EC (async)
requestUpdate @ styles.ts:366
o @ styles.ts:366
m @ styles.ts:366
_ @ styles.ts:366
r @ ha-icon-button-arrow-next.ts:8
value @ hass-loading-screen.ts:11
value @ hass-loading-screen.ts:11
_currentLoadProm.l.then._currentLoadProm @ hass-loading-screen.ts:11
Promise.then (async)
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:366
scheduleUpdate @ styles.ts:366
_$EC @ styles.ts:366
await in _$EC (async)
requestUpdate @ styles.ts:366
o @ styles.ts:366
m @ styles.ts:366
r @ hass-loading-screen.ts:11
r @ app-drawer-layout.js:189
p @ styles.ts:366
T @ styles.ts:366
_$AI @ styles.ts:366
S @ styles.ts:366
update @ styles.ts:366
performUpdate @ styles.ts:366
scheduleUpdate @ styles.ts:366
_$EC @ styles.ts:366
await in _$EC (async)
requestUpdate @ styles.ts:366
o @ styles.ts:366
m @ styles.ts:366
_ @ styles.ts:366
n @ app-drawer-layout.js:189
p @ styles.ts:366
T @ styles.ts:366
_$AI @ styles.ts:366
S @ styles.ts:366
update @ styles.ts:366
value @ home-assistant.ts:34
performUpdate @ styles.ts:366
scheduleUpdate @ styles.ts:366
_$EC @ styles.ts:366
await in _$EC (async)
requestUpdate @ styles.ts:366
set @ styles.ts:366
value @ styles.ts:366
(anonym) @ styles.ts:366
s @ core.0edfd71e.js:1
(anonym) @ core.0edfd71e.js:1
Promise.then (async)
c @ core.0edfd71e.js:1
d @ core.0edfd71e.js:1
subscribe @ core.0edfd71e.js:1
y @ core.0edfd71e.js:1
(anonym) @ core.0edfd71e.js:1
Promise.then (async)
(anonym) @ core.0edfd71e.js:1
(anonym) @ core.0edfd71e.js:1
(anonym) @ core.0edfd71e.js:1`

Can you help me please

**Comment by GerdRuetten** [comment]
Here the same Problem.

Error:
Empty Card

My steps:

1.) Create the directory "/config/www/custom_ui/htc-weather"
2.) Download the ZIP-File here from github
3.) De-Compress the file and transfer it via FTP in binary-Mode to the directory from 1.)
![image](https://user-images.githubusercontent.com/97361636/150762120-1294df35-a878-4ed9-9aaf-c4ddf5c46bdb.png)

4.) Integrate the time_date - Sensor (was integrated bevor and works)
In my configuration.yaml:
```
sensor time_date: !include sensors/time_date.yaml
```

In my sensors/time_date.yaml
```  
  platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'
 ```
5.) place /local/custom_ui/htc-weather/htc-flipclock-weather.js?v=1.3.0 in the lovelance-resources.
![image](https://user-images.githubusercontent.com/97361636/150762517-67dfbd5a-e05c-4ded-a2a9-c944d6cf9786.png)

6.) Create a custom Card on a seperate Lovelance-Register with:
```
type: custom:htc-weather-card
entity: weather.home
sun: sun.sun
```

In the browser-console I get this error:
![image](https://user-images.githubusercontent.com/97361636/150757946-276e00bc-03e7-4602-ab54-c848d0a1c465.png)

I tested Step 5) with and with not the "v=1.3.0"-Parameter.

What's my failure?
What can I do?
