### ISSUE TITLE
Request - sorry to be a pain

### ISSUE THREAD

**Issue by curtisdr** [ibBogdan/lovelace-htc-flipclock-weather#17]
Any chance on getting some direction on how to change "Home" above temp to "Outside", and have it reference an outdoor sensor (entity sensor.jewell_air_temperature)?  Thanks.

**Comment by ibBogdan** [comment]
you can't for now .. but you can use it for the lower right corner: https://github.com/ibBogdan/lovelace-htc-flipclock-weather#with-custom-high_low_entity-entity
