### ISSUE TITLE
Norwegian language

### ISSUE THREAD

**Issue by ToViNi** [ibBogdan/lovelace-htc-flipclock-weather#18]
Great work!

Tried to add a language, Norwegian. Finally got it to work after clearing all Firefox site cache data for HA to get the new regional.js file loaded.
(Danish is similar to Norwegian for date and day names)

	'no': {
		monthNames: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Des'],
		dayNames: ['Søn', 'Man', 'Tir', 'Ons', 'Tor', 'Fre', 'Lør'],
		lang: 'no'
	},

**Comment by ibBogdan** [comment]
added to the lastest version. will push later today
