### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by stevebaele** [ibBogdan/lovelace-htc-flipclock-weather#20]
hi, I´m new to HA, just started yesterday and would love to implement the htc flipclock. But I´m lost on how to do this. Is it possible to help me?

I have created in the configuration.yaml:
 - platform: time_date
    display options
And those seem to work for a different clock.

but where do I create all the other settings? I have installed File Edititor, i guess that is needed for the code.

Sorry for all these basic questions
thanks in advance
Steve

**Comment by ibBogdan** [comment]
you need to edit your lovelace dashboard from inside the homeassistant app. top right corner you see 3 dots.. click on that on edit dashboard. from there you need to add a custom custom card and paste the code from the docs
