### ISSUE TITLE
Custom element doesn't exist: htc-weather-card.

### ISSUE THREAD

**Issue by Ranger3368** [ibBogdan/lovelace-htc-flipclock-weather#5]
Hi, Bogdan! 
I've noticed you fantastic card (years ago I had an HTC smartphone with that widget on the home page... Sigh! ;-P). I've followed your installation guide, but right now I didn't be able to make it works... I'm running Home Assistant Core on Raspbian. Could you help me?

**Comment by ibBogdan** [comment]
Hey,
Sure.. let` do some debugging :d
Open up the console, refresh the page and answer these questions :D

1: did you add the time_date sensor?
2: do you have any errors? (if you have them.. send me a screenshot with all of them)
3: does this appear in the console tab:  HTC Flip Clock  1.2.1
4: in the network tab do you see the following?
htc-flipclock-weather.js?v1.2.1
themes.js?v1.0.1
regional.js?v1.1.4

That`s it for now.. thanks

**Comment by Ranger3368** [comment]
Wow! Such a fast answer! Thank you very much!
:-)
:-)
:-)
:-)
:-)

------ Messaggio originale ------
Da: "Bocioaca Bogdan" <notifications@github.com>
A: "ibBogdan/lovelace-htc-flipclock-weather" 
<lovelace-htc-flipclock-weather@noreply.github.com>
Cc: "Ranger3368" <ranger3368@gmail.com>; "Author" 
<author@noreply.github.com>
Inviato: 26/01/2021 19:18:06
Oggetto: Re: [ibBogdan/lovelace-htc-flipclock-weather] Custom element 
doesn't exist: htc-weather-card. (#5)

>
>Hey,
>Sure.. let` do some debugging
>:d
>
>Open up the console, refresh the page and answer these questions
>:D
>
>1: did you add the time_date sensor?
>
Yes

then I've added the reference in lovelace_ui.yaml


and copied the zip content on this path:


>2: do you have any errors? (if you have them.. send me a screenshot 
>with all of them)
>
Only when I create a card in lovelace, this is what I get:


>
>3: does this appear in the console tab: HTC Flip Clock 1.2.1
>
>4: in the network tab do you see the following?
>
>htc-flipclock-weather.js?v1.2.1
>themes.js?v1.0.1
>regional.js?v1.1.4
>
Ehm... what you mean for console and network tab?
Perhaps in the translation those are called in a different way?


>That`s it for now.. thanks
>

Once again, thank you very much for you help!

Marco

-- 
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by ibBogdan** [comment]
By console and network tab i mean that you need to open developer tools (in chrome) by pressing F12 and you`ll see this
![image](https://user-images.githubusercontent.com/12171894/106303321-ac2ed700-6262-11eb-87ec-7e389d1ab3df.png)

I`m interested in the Console tab errors and the answers from the network tab questions, please

**Comment by Ranger3368** [comment]
Thanks for replying, Bogdan.

> 3: does this appear in the console tab: HTC Flip Clock 1.2.1
No, this does not appear... :-(
[image: image.png]

> 4: in the network tab do you see the following?
> htc-flipclock-weather.js?v1.2.1
> themes.js?v1.0.1
> regional.js?v1.1.4

No, those neither...
[image: image.png]

Thanks again,

Marco

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno ven 29 gen 2021 alle ore 17:50 Bocioaca Bogdan <
notifications@github.com> ha scritto:

**Comment by michal-maly** [comment]
Hi man can you help me withh your nice module ?
https://i.ibb.co/T0ykmk5/pocasi.png
i see only fetching weather :(

**Comment by Ranger3368** [comment]
Hi, Bogdan. I made some changes and solved all that plenty of errors listed in the image of the console tab above. Now there are not error showings. Anyway, I didn't be able to load the file requested by your plugin (htc-flipclock-weather.js?v1.2.1 - themes.js?v1.0.1 and regional.js?v1.1.4).

**Comment by ibBogdan** [comment]
just out of curiosity.. did you add the correct path to the plugin in Configuration -> Lovelace Dashboards -> Resources ?

**Comment by Ranger3368** [comment]
Yes. There and also in ui-lovelace.yaml

![image](https://user-images.githubusercontent.com/76102600/106894668-8f295680-66ef-11eb-963b-f5094c0b3c8a.png)

**Comment by ibBogdan** [comment]
ok, that seems correct.
on your pi does the path look like this homeassistant_folder(where configuration.yaml is)/www/custom_ui/htc-weather/  ?

**Comment by Ranger3368** [comment]
IT WORKS! :)))
The problem was a - instead of _ in the forder name... OMG, what a dumb I am! :-D :-D

Now a last little question. Why I can only see UTC time, even if I change the sensor.time_utc in sensor.time?

**Comment by ibBogdan** [comment]
:)) gooood :D
because that sensor return utc time. user svrOffset in settings to set it to your timezone. it`s in seconds.

**Comment by Ranger3368** [comment]
Is there a way to resize the images inside the card? When displayed in the companion app (android 11) the card border is shown correctly, but the images inside it are cropped. Should be possible to add a css "width" and "height" with a value=auto, so the image will be resized due the display resolution?

**Comment by Ranger3368** [comment]
![Screenshot_2021-02-04-23-06-09-763_io homeassistant companion android](https://user-images.githubusercontent.com/76102600/106961406-d3dbde80-673d-11eb-8b34-6c9a081c5e85.jpg)
