### ISSUE TITLE
Italian language

### ISSUE THREAD

**Issue by djgragra** [ibBogdan/lovelace-htc-flipclock-weather#7]
[regional.js.zip](https://github.com/ibBogdan/lovelace-htc-flipclock-weather/files/5945412/regional.js.zip)
I added the Italian language in the regional.js file but unfortunately it doesn't work.
What else needs to be changed?

**Comment by vittorio1968** [comment]
> [regional.js.zip](https://github.com/ibBogdan/lovelace-htc-flipclock-weather/files/5945412/regional.js.zip)
> I added the Italian language in the regional.js file but unfortunately it doesn't work.
> What else needs to be changed?

Per la lingua italiana una volta che hai modificato il file regional modifica anche  la riga  6 del file  
htc-flipclock-weather.js
da così:
import { regional } from './regional.js?v1.1.4';
a così:
import { regional } from './regional.js?v1.1.5';

**Comment by djgragra** [comment]
> > [regional.js.zip](https://github.com/ibBogdan/lovelace-htc-flipclock-weather/files/5945412/regional.js.zip)
> > I added the Italian language in the regional.js file but unfortunately it doesn't work.
> > What else needs to be changed?
> 
> Per la lingua italiana una volta che hai modificato il file regional modifica anche la riga 6 del file
> htc-flipclock-weather.js
> da così:
> import { regional } from './regional.js?v1.1.4';
> a così:
> import { regional } from './regional.js?v1.1.5';

Funziona. Grazie!

**Comment by djgragra** [comment]
@vittorio1968 
Se sei interessato ad aggiungere il mese ho modificato le seguenti righe del file htc-flipclock-weather.js

Riga 361 (o 360)
da così
forecast    += `<p class="dayname">${regional[config.lang]['dayNames'][d_date.getDay()]}&nbsp;${d_date.getDate()}</p>

a così
forecast += `<p class="dayname">${regional[config.lang]['dayNames'][d_date.getDay()]}&nbsp;${d_date.getDate()}&nbsp;${regional[config.lang]['monthNames'][d_date.getMonth()]}</p>

Riga 380 (o 379)
da così
var today_date = `${regional[config.lang]['dayNames'][new Date().getDay()]}&nbsp;${new Date().getDate()}`;

a così
var today_date = `${regional[config.lang]['dayNames'][new Date().getDay()]}&nbsp;${new Date().getDate()}&nbsp;${regional[config.lang]['monthNames'][new Date().getMonth()]}`;

Attenzione che io sto usando la versione 1.2.1 comunque basta che cerchi nel file dayNames e trovi le righe, vedrai invece che non troverai monthNames

**Comment by ibBogdan** [comment]
merged it. thank you
