### ISSUE TITLE
AM/PM & Wrong time on iPad

### ISSUE THREAD

**Issue by AseKarlsson** [ibBogdan/lovelace-htc-flipclock-weather#8]
Hi,
Just found this card and love it.

I have 2 issues that I am not able to solve:
1. I have set "am_pm: false" but at the bottom of the card that shows when sun is rising and going down it is still AM/PM, can this be configured?
2. The clock is OK on my computer, but on my iPad it is 2 hours in front. I have checked the region of my iPad to be Sweden and also that the clock is right, any ideas?

Thanks,
Ase

**Comment by ibBogdan** [comment]
Hey,
1: that`s from the sun entity you need to see to to set that up.
2: i think that`s an issue with the browser. can you download the app and see if it works. i had the same issue at first on the browser.

**Comment by AseKarlsson** [comment]
Hi Bocioaca,
1. I will check this, I cannot see a direct sun attribute that could influence this, but many issues with 12/24 hour clock in HA.
2. I am using the latest App from AppStore.

**Comment by AseKarlsson** [comment]
Hi Bocioaca,

No ideas how to proceed with point 2?

**Comment by ibBogdan** [comment]
I`m sorry, but i really don`t know. The plugin takes the time based on your device. So might be that some settings are wrong there.
